input.onButtonPressed(Button.A, function () {
    turtle.setPosition(0, 0)
    turtle.pen(TurtlePenMode.Down)
    turtle.turnRight()
    turtle.forward(4)
    turtle.turnRight()
    turtle.forward(4)
    turtle.turnRight()
    turtle.forward(4)
    turtle.turnRight()
    turtle.forward(3)
    turtle.turnRight()
    turtle.forward(3)
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnRight()
    turtle.forward(2)
    turtle.turnRight()
    turtle.forward(1)
    turtle.turnRight()
    turtle.forward(1)
    turtle.setBrightness(0)
    turtle.turnLeft()
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(1)
    turtle.turnLeft()
    turtle.forward(2)
    turtle.turnLeft()
    turtle.forward(2)
    turtle.turnLeft()
    turtle.forward(3)
    turtle.turnLeft()
    turtle.forward(3)
    turtle.turnLeft()
    turtle.forward(4)
    turtle.turnLeft()
    turtle.forward(4)
    turtle.turnLeft()
    turtle.forward(4)
})
basic.forever(function () {
	
})
